const skillsdata = [
  {
    category: "Core Engineering & ML",
    skills: [
      "Machine Learning",
      "Deep Learning",
      "NLP (Natural Language Processing)",
      "Data Structures & Algorithms",
    ],
    image: "./ml.svg",
  },
  {
    category: "Responsible AI & Safety",
    skills: [
      "AI Guardrails",
      "Prompt Injection Defense",
      "Jailbreak Mitigation",
      "PII Masking & Redaction (105+ entities)",
      "Toxicity Filtering",
      "Red Teaming",
      "Adversarial Testing",
      "OWASP Top 10 for LLMs",
      "Supply Chain Security",
    ],
    image: "./responsible-ai.svg",
  },
  {
    category: "Model Alignment & Fine-Tuning",
    skills: [
      "Supervised Fine-Tuning (SFT)",
      "Unsloth",
      "Small Language Model (SLM) Optimization",
      "Safety Benchmarking",
      "Dataset Curation",
      "Synthetic Data Generation",
      "Model Robustness Evaluation",
    ],
    image: "./fine-tuning.svg",
  },
  {
    category: "Generative AI & LLM Frameworks",
    skills: [
      "Large Language Models (LLMs)",
      "LangChain",
      "LangGraph",
      "Model Context Protocol (MCP)",
      "vLLM",
      "Gemini CLI",
      "Agentic AI",
      "RAG",
    ],
    image: "./ai-agents.svg",
  },
  {
    category: "Compute & Infrastructure",
    skills: [
      "NVIDIA H100/B200 GPU Clusters",
      "Slurm Workload Manager",
      "Distributed Compute",
      "Google Cloud Run (GCP)",
      "Virtual Machines (Linux)",
      "Docker",
    ],
    image: "./api.svg",
  },
  {
    category: "Security & Data Libraries",
    skills: [
      "PyTorch",
      "Scikit-learn",
      "Pandas",
      "NumPy",
      "Matplotlib",
      "Static Application Security Testing (SAST)",
      "YARA Rules",
      "Regex Pattern Matching",
      "JWT",
      "Bandit",
      "Semgrep",
    ],
    image: "./deep-learning.svg",
  },
  {
    category: "Languages & Full-Stack",
    skills: [
      "Python",
      "JavaScript",
      "React.js",
      "Node.js",
      "Express.js",
      "REST APIs",
      "JSON-RPC",
      "MongoDB",
      "Cloudinary",
    ],
    image: "./reactjs.svg",
  },
  {
    category: "Tools & Platforms",
    skills: [
      "Git",
      "Linux",
      "Hugging Face",
      "GitHub Copilot",
      "Claude Code",
      "Azure AI Services",
    ],
    image: "./git.svg",
  },
];

export default skillsdata;
